### ISSUE TITLE
IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by songbowang125** [dhcai21/RVHaplo#1]
Hi, I was running RVHaplo with my own data, but i met the following errors, the log was:

count nucleotide occurrence
SNV detection
Traceback (most recent call last):
  File "./src/two_binomial.py", line 44, in <module>
    beta = ref_init[1]
IndexError: invalid index to scalar variable

**Comment by dhcai21** [comment]
Hi,

Can you send me the data for checking the error? My email is "dhcai2-c@my.cityu.edu.hk". Thanks.

Dehan

**Comment by dhcai21** [comment]
I have tested RVHaplo on my own data. It output the result successfully. Can you test the data from the link?
https://drive.google.com/drive/folders/1A4I722MO4Ujnvu_B3pugq6v6N4t1koHd?usp=sharing

**Comment by songbowang125** [comment]
I find the reason. It was beacause this command: 
samtools view -h -F 0x900 $file_sam > $unique_sam in line 375 of rvhaplo.sh 
-F 0x900 only take primary alignments but in my data, the reads were supplementary alignments, so this command outputed nothing.

Thanks.

**Comment by dhcai21** [comment]
Thank you for telling me the reason. 

Dehan
