### ISSUE TITLE
All exit commands are `exit 1`

### ISSUE THREAD

**Issue by jonathan-bravo** [dhcai21/RVHaplo#4]
Hello,

I noticed that every exit in the shell script is an `exit 1` indicating an error. However, I am running RVHaplo in a pipeline and even when the program looks like it completes correctly it throws an error halting the whole pipeline. I am wondering if some of the exit commands should be `exit 0` instead of `exit 1`.

Cheers,
Johnny

**Comment by dhcai21** [comment]
Hi Johnny,

Thanks for pointing that out. You are correct that most commands should be "exit 0". I will update the code. Thanks again for bringing this to our attention.

Best,
Dehan

**Comment by jonathan-bravo** [comment]
Thanks for the quick reply/ changes! 

Another thing I noticed was, in the python scripts you used `exit()` at the end. However, I believe this throws an error (like calling `exit 1`). I just did a quick search and it looks like it might be better to use `sys.exit(0)` to call `exit 0` from within the script.
It might also be unnecessary as it looks like all the commands finish running and the `exit` is just at the end? I am not totally sure as I have not tested each script individually.

Cheers,
Johnny

**Comment by dhcai21** [comment]
Hi Johnny,

Thank you for your suggestion. I appreciate your feedback on the `exit()` command.  Both `exit()` and `sys.exit(0)` will terminate the Python interpreter and exit the program with a status code of 0, indicating successful execution. Therefore, using `exit()` will not affect the tool's running.

However, I will keep your suggestion in mind and modify the code if necessary. I appreciate your attention to detail and willingness to provide feedback.

Thanks again for your input, and please feel free to let me know if you find anything else that needs to be addressed.

Have a great day!

Dehan

**Comment by jonathan-bravo** [comment]
I will make sure to keep you updated as I run the tool in my pipeline/ if I notice anything else. Thank you again for your quick response!

Johnny
