### ISSUE TITLE
RVHaplo and SARS-CoV-2 data

### ISSUE THREAD

**Issue by AndreaAguadoM** [dhcai21/RVHaplo#5]
Hello, my name is Andrea and I am a bioinformatician from Spain. 

Currently, I am working with SARS-CoV-2 data obtained using Nanopore sequencing, and I am interested in using RVHaplo for haplotype identification. Is it reliable for SARS-CoV-2 data already? 

Thanks in advance!

**Comment by dhcai21** [comment]
Hi Andrea,

Thank you for contacting me regarding RVHaplo and SARS-CoV-2 data. We only conducted a simulated experiment on data containing two SARS-CoV-2 variants (the Delta and Omicron variants). Our results showed that RVHaplo and our other method, HaploDMF, could reconstruct the haplotypes to a certain extent. I recommend you refer to our HaploDMF paper's supplementary material for more information: https://doi.org/10.1093/bioinformatics/btac708.

Dehan

**Comment by AndreaAguadoM** [comment]
Okay, we will try haplodmf instead.
Thanks for your help!
